Plotting issue in image_stitch.py
`fig` is used as a variable for the whole figure, and then each of the subplots. This mean that `fig.savefig` results in the error `AttributeError: 'AxesSubplot' object has no attribute 'savefig'`