dem_error: bugfix on the step func
Fix the bug that the input step function date in cmd and template file was NOT corrected passed into the design matrix, due to the inconsistent usage of the variable naming.

+ rename stepFuncDate to stepDate in all `dem_error` related code and docs

+ prep_hyp3: add hdf-eos5 metadata extraction

+ docs/demo: use list to break lines