dem_error: skip pixel with nan value
dem_error:
1. skip pixel with nan value in any interferogram, instead of in all interferograms before.

2. ignore input non-existed default exclude_date.txt file

ptime/read_date_list(): support input list contains non-existed text file.