dem_error: set `cond=1e-8` to fix abnormal fit residual + add unit test (#890)
+ `dem_error`: fix abnormal residual TS with default phase velocity mode
   - estimate_dem_error(): switch cutoff value of the least squares solution from 1e-15 to 1e-8, to avoid abnormal high TS residual value, when the phase velocity mode is turned ON by default. Tests (based on the new unit test script) shows this change has no impact on the estimation result at all, which is good.
   - set `debug_mode` as global variable to be test a specific pixel given Y/X easily.

+ add `tests/dem_error.py`, to test the DEM error estimation / correction in both scenarios (simple linear and complex non-linear) for one pixel.
   - add to circle CI testing

+ `ifgram_inversion`: rename/shortern the default output filenames for ionStack.h5

+ `tropo_pyaps3`: improved auto-skip/run checks
   - skip dload if ERA5.h5 already exists
   - skip re-applying correction if corrected displacement exists and is newer
   - print out msg adjustment