dem_error: do not write step_model for simplicity
+ dem_error: do not write step_model into file/disk because:
1. the step function estimation is now supported via timeseries2velocity.h5 and the latter has more powerful functionality
2. the step model HFD5 file from dem_error.py is different from the one from ts2vel.h5 and the latter is preferred for its simplicity.

+ drop the common operations support in the following scripts of timeseriesStepModel.h5 file, which sometimes has one date in the time dimension:
   - geocode.py
   - mask.py
   - multilook.py
   - subset.py

+ dem_error: replace split2boxes with cluster.split_box2sub_boxes()

test_sbApp: plot velocity alone for snap and aria also