`euler_pole`: add PMM plotting functions (#935)
* euler_pole.py: add PMM plotting functions

+ add plate boundary files from GSRMv2.1 and MORVEL56

+ functions to read the boundary files and plot

* updates

* + plate_motion.py: ITRF2014_PMM use full names as keys

+ Consistent NNR model file:
	- src/mintpy/data/plate_boundary/GSRMv2.1/nnr.csv
	- src/mintpy/data/plate_boundary/MRVL56/nnr.csv
	- use camelCase plate names (but caplitalize the first character)

+ Consistent plate boundary file:
	- src/mintpy/data/plate_boundary/GSRMv2.1/plate_outlines.txt
	- src/mintpy/data/plate_boundary/MRVL56/plate_outlines.txt
	- use '> ' before plate abbv. names, good for GMT
	- use longitude, latitude for the columns, good for GMT

+ remove useless script: src/mintpy/data/plate_boundary/GSRMv2.1/split_bnds.py

+ update full reference in README.md under src/mintpy/data/plate_boundary/

+ euler_pole.py: update read_plate_attributes() read_plate_outlines()

* bugfix for codacy and unit_test checks

* ionex: attempt to fix the unit test

attempt to fix the unit test error below:

```
Testing /root/tools/MintPy/tests/objects/ionex.py
Traceback (most recent call last):
  File "/root/tools/MintPy/tests/objects/ionex.py", line 110, in <module>
    test_get_ionex_value()
  File "/root/tools/MintPy/tests/objects/ionex.py", line 93, in test_get_ionex_value
    tec_val = ionex.get_ionex_value(
  File "/root/tools/miniconda3/lib/python3.10/site-packages/mintpy/objects/ionex.py", line 102, in get_ionex_value
    tec_val = interp_3d_maps(
  File "/root/tools/miniconda3/lib/python3.10/site-packages/mintpy/objects/ionex.py", line 184, in interp_3d_maps
    tec_val = interpolate.interpn(
  File "/root/tools/miniconda3/lib/python3.10/site-packages/scipy/interpolate/_rgi.py", line 654, in interpn
    return interp(xi)
  File "/root/tools/miniconda3/lib/python3.10/site-packages/scipy/interpolate/_rgi.py", line 331, in __call__
    indices, norm_distances = self._find_indices(xi.T)
  File "/root/tools/miniconda3/lib/python3.10/site-packages/scipy/interpolate/_rgi.py", line 499, in _find_indices
    return find_indices(self.grid, xi)
  File "_rgi_cython.pyx", line 95, in scipy.interpolate._rgi_cython.find_indices
  File "stringsource", line 660, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 350, in View.MemoryView.memoryview.__cinit__
ValueError: ndarray is not C-contiguous
```

* ionex: bugfix attempt no. 2

* test git rename via jupyter

* Revert "test git rename via jupyter"

This reverts commit b62d7487ca8c23a884ba6943b9a0395ea600a763.

* Revert "ionex: bugfix attempt no. 2"

This reverts commit 22f88ba496d453b876f2e311c87086f6e2484e88.

* Revert "ionex: attempt to fix the unit test"

This reverts commit 5e491abe9251cfd628c3f2421fd42b331981caa5.

* remove the unnecessary plate name abbreviation in `plate_motion.py -h`

* filenames and variable changes:

+ read GSRM and MORVEL56 model parameters (abbrev) from built-in dictionary

+ GSRM and MORVEL56 PMM files (csv) are not in used, but keep them for bookkeeping

+ folder names hosting plate boundaries are modified

+ use original file names for plate boundaries files (consistent with the source)

* structure changes

refer to: https://github.com/insarlab/MintPy/wiki/plate-motion-package

+ euler_pole.py: put pmm definitions here, plate abbv are upper case

+ cli/plate_motion.py: remove pmm definitions

+ plate_boundary/*/nnr.csv: delete them

+ to-do: move --plate to --om-cart from mintpy.cli.plate_motion to mintpy.plate_motion

* move ITRF2014_PMM dependent codes to src/mintpy/plate_motion.py

src/mintpy/cli/plate_motion.py will not need this dictionary

* src/mintpy/plate_motion.py

from mintpy.objects.euler_pole import ITRF2014_PMM

* fix import in tests/objects/euler_pole.py

* plate_boundary dir/file rename with shell cmds to reproduce

+ use `MORVEL` instead of `MORVEL56` for the folder name, as it's generic for MORVEL and NNR-MORVEL56, to be consistent of using GSRM, instead of GSRMv2.1

+ rename both data files as `plate_outlines.gmt` with shell commands in the README for easy produce

+ euler_pole:
   - update data file path from above changes
   - use `GSRM_V21_PMM` and `NNR_MORVEL56_PMM` for more precise info

* codacy fix

* euler_pole refactor - part 1

* codacy fix

* euler_pole refactor part 2

+ use center_lalo to replace center_lat/lon
+ use satellite_height directly, instead of zoom
+ map center priority: direct input arg > pts_lalo > polygon centroid
+ remove vu as it's not used

* updates to the plate boundary files:

+ use the original downloaded files

+ extensions as .lalo or .lola

+ modify euler_pole.py accordingly

* update

* read_plate_outline: return as shapely object

Co-authored-by: Zhang Yunjun <yunjunzgeo@gmail.com>